# Generated by Django 4.2.1 on 2023-06-07 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Volume', '0003_added_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pin',
            name='price',
        ),
    ]
